name: CI - Master
  
on:
    push:
      branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout #checkout code from repository, so code downloaded in runner.  
      uses: actions/checkout@v4.2.2  
    - name: Setup Node.js environment #setup nodejs in our runner
      uses: actions/setup-node@v4.1.0        
      with:
        node-version: 22.x 
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_PRIVATE_KEY" > ./deploy.key
        sudo chmod 600 ./deploy.key
        echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
      shell: bash
      env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}

    # (optional - only needed if your config uses environment variables)
    - name: Create env file
      run: |
          touch .env
    #      echo DATABASE_ADDRESS=${{ secrets.DATABASE_ADDRESS }} >> .env

    - name: Install PM2
      run: npm i -g pm2@latest

    - name: Deploy
      run: env $(cat .env | grep -v \"#\" | xargs) pm2 deploy ecosystem.config.cjs
        # Or alternately, put this deploy script in your package.json's scripts and run it using yarn/npm:
        # run: yarn deploy yyy
